### ISSUE TITLE
Setup Instructions don't work

### ISSUE THREAD

**Issue by silentrob** [erelsgl/nlu-server#41]
After cloning and installing I'm getting.

```
/Users/me/projects/nlu-server/node_modules/serialization/index.js:93
		throw new Error("Error in creating new Object from function in string: "+err
		      ^
Error: Error in creating new Object from function in string: TypeError: Cannot read property 'bind' of undefined
```
`npm test` also throws an error looking for bind.
I will keep investigating but thought I would flag it for you.

**Comment by sharesynth** [comment]
Having trouble with installing as well:

Running on Node v4.2.3.
Employer-usa
createNewObjectString: (function createNewClassifier()
{
	var defaultClassifier = require('/Users/username/projects/nlu/nlu-server'+'/classifiers').defaultClassifier
	return new defaultClassifier()
})
dirname: /Users/username/projects/nlu/nlu-server
/Users/username/projects/nlu/nlu-server/node_modules/serialization/index.js:93
		throw new Error("Error in creating new Object from function in string: "+error);
		^

Error: Error in creating new Object from function in string: Error: Cannot find module 'md5'
    at Object.exports.fromJSON (/Users/username/projects/nlu/nlu-server/node_modules/serialization/index.js:93:9)
    at Object.exports.fromString (/Users/username/projects/nlu/nlu-server/node_modules/serialization/index.js:63:17)
    at /Users/username/projects/nlu/nlu-server/servertranslate.js:79:52
    at Array.forEach (native)
    at Object.<anonymous> (/Users/username/projects/nlu/nlu-server/servertranslate.js:70:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
